#!/bin/bash

# Copies needed mod files, cooks, packs and creates metadata
# Usage: first argument is the path to the mod in form: /[driveLetter]/[restOfThePath]
# no '/' at the end
#
# Requirements:
# 1) wcc_lite in PATH
# 2) Mod directory structure:
#      [modWorkDir]/Cooked (cooked files)
#	   [modWorkDir]/Uncooked (uncooked files)
#	   [modWorkDir]/Packed/[modReadyFolder] (mod package)
#

# SCRIPT FILES BEGIN
scriptFile[0]="/game/actor.ws"
scriptFile[1]="/game/player/playerWitcher.ws"
scriptFile[2]="/game/gameplay/ability/PlayerAbilityManager.ws"
scriptFile[3]="/game/gameplay/damage/damageManagerProcessor.ws"
scriptFile[4]="/game/gameplay/effects/effects/mutagens/mutagenEffect.ws"
scriptFile[5]="/game/gameplay/effects/effects/mutagens/mutagen15.ws"

scriptFile[6]="/game/components/inventoryComponent.ws"
scriptFile[7]="/game/gui/menus/characterMenu.ws"
scriptFile[8]="/game/gui/_old/components/guiTooltipComponent.ws"
# SCRIPT FILES END

# ASSET FILES BEGIN
assetFile[0]="/gameplay/abilities/geralt_skills.xml"
assetFile[1]="/gameplay/abilities_plus/geralt_skills.xml"
assetFile[2]="/gameplay/abilities/effects_mutagens.xml"
assetFile[3]="/gameplay/abilities_plus/effects_mutagens.xml"
assetFile[4]="/dlc/bob/data/gameplay/abilities/effects_ep2.xml"
assetFile[5]="/dlc/bob/data/gameplay/abilities_plus/effects_ep2.xml"
assetFile[6]="/dlc/bob/data/gameplay/abilities/geralt_skills_ep2.xml"
assetFile[7]="/dlc/bob/data/gameplay/abilities_plus/geralt_skills_ep2.xml"
# ASSET FILES END

set -e

if [ -z $1 ]
then
    echo "Wrong path to the mod!"
	exit
fi

modContentPath=$1"/Packed/modGrandBalanceRepairAlchemy/content"

inXMLPath="Uncooked"
inScriptPath="Script/scripts"

outScriptPath=$modContentPath"/scripts"

outXmlPath1=$1"/Uncooked"
outXmlPath2=$1"/Cooked"

for i in "${scriptFile[@]}"
do
	cp $inScriptPath$i $outScriptPath$i
done

for i in "${assetFile[@]}"
do
	cp $inXMLPath$i $outXmlPath1$i
	cp $inXMLPath$i $outXmlPath2$i
done

echo "Files copied OK."

wcc_lite cook -platform=pc -mod=$outXmlPath1 -basedir=$outXmlPath1 -outdir=$outXmlPath2
wcc_lite pack -dir=$outXmlPath2 -outdir=$modContentPath
wcc_lite metadatastore -path=$modContentPath
